#服务端口号
server:
    port: 8110
#服务名
spring:
  application:
    name: dev
  profiles:
    active: dev
  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
#HIkari 是SpringBoot 2.0之后默认整合的数据库连接池，比druid更快的数据库连接池
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #连接池名称
    hikari:
      pool-name: GuliHikariPool
    #最大连接数，小于等于0会被重置为默认值10；大于0小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
    #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
    #最小空连接，默认值10，小于0或者大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
    #空连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0
    #只有空连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000

    #连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟，设置应该比mysql设置的超时时间短
      max-lifetime: 540000
    #连接测试查询
      connection-test-query: SELECT 1

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml

  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #逻辑删除
  global-config:
    db-config:
      #value=1已删除
      logic-delete-value: 1
      #value=0未删除
      logic-not-delete-value: 0
      # 以下配置均有默认值,可以不设置
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL

